name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install dependencies with conda
        run: conda install -c conda-forge jupyter nbconvert

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute music_mood_nc.ipynb --output music_mood_nc.ipynb
